<%-- 
    Document   : shop
    Created on : Oct 29, 2023, 10:47:06 PM
    Author     : akshaydatir
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <%

                out.println("<!DOCTYPE html>");
                out.println("<html lang=" + "en" + ">");
                out.println("<head>");
                out.println("<meta charset=" + "UTF - 8 " + ">");
                out.println("<meta name=" + "viewport" + " content=" + "width = device - width, initial - scale = 1.0" + ">");
                out.println("<title>Shopping List</title>");
                out.println("<style>");
                out.println("        container {");
                out.println("        padding: 10px;");
                out.println("        display: flex;");
                out.println("        justify-content: space-around; ");
                out.println("        align-items: left; ");
                out.println("        }");
                out.println("");
                out.println("        .computer{");
                out.println("            position: absolute;");
                out.println("            top: 70px;");
                out.println("            right: 800px;");
                out.println("            display:none;");
                out.println("       ");
                out.println("        }");
                out.println("");
                out.println("        .music{");
                out.println("            position: absolute;");
                out.println("            top: 70px;");
                out.println("            right: 800px;");
                out.println("            display:none;");
                out.println("           ");
                out.println("        }");
                out.println("        .book{");
                out.println("            position: absolute;");
                out.println("            top: 70px;");
                out.println("            right: 800px;");
                out.println("            display:none;");
                out.println("     ");
                out.println("        }");
                out.println("        .display{");
                out.println("            position: absolute;");
                out.println("            top: 70px;");
                out.println("            right: 800px;");
                out.println("            display:none;");
                out.println("     ");
                out.println("        }");
                out.println("        .cart{");
                out.println("           float: right;");
                out.println("           ");
                out.println("            ");
                out.println("        }");
                out.println(".submit{ position: absolute;top:150px;right: 800px; }");
                out.println("    </style>");
                out.println("</head>");
                out.println("<body>");
                out.println("<form action=\"/HW4/shop.htm\" method=\"POST\">");
                out.println("    <h2>Shopping List</h2>");
                out.println("    <div class=" + "container" + ">");
                out.println("        <div class=" + "left" + ">");
                out.println("<a href=" + "#" + " id=" + "showHideLink1" + ">Music</a>");
                out.println("<br>");
                out.println("<a href=" + "#" + " id=" + "showHideLink2" + ">Computers</a>");
                out.println("<br>");
                out.println("<a href=" + "#" + " id=" + "showHideLink3" + ">Books</a>");
                out.println("</div>");
                out.println("</div>");
                out.println("");
                out.println("<div class=" + "computer" + ">");
                out.println("<label>");
                out.println("<input type=\"checkbox\" name=\"comp\" value=\"Mac Book - $1500.00\">");
                out.println("Mac Book - $1500.00");
                out.println("</label>");
                out.println("<br>");
                out.println("<label>");
                out.println("<input type=\"checkbox\" name=\"comp\" value=\"Leneovo - $1200.00\">");
                out.println("Leneovo - $1200.00");
                out.println("</label>");
                out.println("<br>");
                out.println("<label>");
                out.println("<input type=\"checkbox\" name=\"comp\" value=\"DELL - $1300.00\">");
                out.println("DELL - $1300.00");
                out.println("</label>");
                out.println("</div>");
                out.println("");
                out.println("<div class=" + "music" + ">");
                out.println("<label>");
                out.println("<input type=\"checkbox\" name=\"music\" value=\"Rock Music - $100.00\">");
                out.println("Rock Music - $100.00");
                out.println("</label>");
                out.println("<br>");
                out.println("<label>");
                out.println("<input type=\"checkbox\" name=\"music\" value=\"JAZZ Music - $200.00\">");
                out.println("JAZZ Music - $200.00");
                out.println("</label>");
                out.println(" <br>");
                out.println("  <label>");
                out.println("<input type=\"checkbox\" name=\"music\" value=\"Hip-Hop Music - $120.00\">");
                out.println(" Hip-Hop Music - $120.00");
                out.println(" </label>");
                out.println("  </div>");
                out.println("<div class=" + "book" + ">");
                out.println(" <label>");
                out.println("<input type=\"checkbox\" name=\"book\" value=\"Harry Potter - $100.00\">");
                out.println("  Harry Potter - $100.00");
                out.println(" </label>");
                out.println(" <br>");
                out.println("  <label>");
                out.println("<input type=\"checkbox\" name=\"book\" value=\"Rich Dad Poor Dad - $60.00\">");
                out.println("  Rich Dad Poor Dad - $60.00");
                out.println("  </label>");
                out.println("  <br>");
                out.println(" <label>");
                out.println("<input type=\"checkbox\" name=\"book\" value=\"Change Habits - $90.00\">");
                out.println("Change Habits - $90.00");
                out.println("  </label>");
                out.println("  </div>");
                out.println("<input type=\"hidden\" name=\"param\" value=\"view\">");
                out.println("<div class=" + "display" + ">");
                out.println("Items added succesfully!!!!");
                out.println("</div>");
                out.println("<div class=" + "submit" + ">");
                out.println(" <button type=\"button\" id=\"cart\">Add to Cart</button>");
                out.println("<div class=" + "cart" + ">");
                out.println(" <button type=\"Submit\">View Cart</button>");
                out.println("</div>");
                out.println("</form>");
                out.println("    <script>");
                out.println("        // JavaScript to toggle visibility of the shopping list");
                out.println("        document.getElementById('cart').addEventListener('click', function() {");
                out.println("            var display = document.querySelector('.display');");
                out.println("            var shoppingList1 = document.querySelector('.music');");
                out.println("            var shoppingList2 = document.querySelector('.book');");
                out.println("            var shoppingList3 = document.querySelector('.computer');");

                out.println("            if (display.style.display === 'none') {");
                out.println("                display.style.display = 'block';");
                out.println("                shoppingList1.style.display = 'none';");
                out.println("                shoppingList2.style.display = 'none';");
                out.println("                shoppingList3.style.display = 'none';");
                out.println("               ");
                out.println("            }else {");
                out.println("                display.style.display = 'none';");
                out.println("                shoppingList1.style.display = 'none';");
                out.println("                shoppingList2.style.display = 'none';");
                out.println("                shoppingList3.style.display = 'none';");
                out.println("            }");
                out.println("        });");
                out.println("        document.getElementById('showHideLink1').addEventListener('click', function() {");
                out.println("            var display = document.querySelector('.display');");
                out.println("            var shoppingList1 = document.querySelector('.music');");
                out.println("            var shoppingList2 = document.querySelector('.book');");
                out.println("            var shoppingList3 = document.querySelector('.computer');");
                out.println("            if (shoppingList1.style.display === 'none') {");
                out.println("                shoppingList1.style.display = 'block';");
                out.println("                display.style.display = 'none';");
                out.println("                shoppingList2.style.display = 'none';");
                out.println("                shoppingList3.style.display = 'none';");
                out.println("                display.style.display = 'none';");
                out.println("               ");
                out.println("            }else {");
                out.println("                display.style.display = 'none';");
                out.println("                shoppingList1.style.display = 'none';");
                out.println("                shoppingList2.style.display = 'none';");
                out.println("                shoppingList3.style.display = 'none';");
                out.println("            }");
                out.println("        });");
                out.println("        document.getElementById('showHideLink2').addEventListener('click', function() {");
                out.println("            var shoppingList1 = document.querySelector('.computer');");
                out.println("            var display = document.querySelector('.display');");
                out.println("            var shoppingList2 = document.querySelector('.music');");
                out.println("            var shoppingList3 = document.querySelector('.book');");
                out.println("            if (shoppingList1.style.display === 'none') {");
                out.println("                shoppingList1.style.display = 'block';");
                out.println("                shoppingList2.style.display = 'none';");
                out.println("                shoppingList3.style.display = 'none';");
                out.println("                display.style.display = 'none';");
                out.println("            } else {");
                out.println("                display.style.display = 'none';");
                out.println("                shoppingList1.style.display = 'none';");
                out.println("                shoppingList2.style.display = 'none';");
                out.println("                shoppingList3.style.display = 'none';");
                out.println("                ");
                out.println("            }");
                out.println("        });");
                out.println("        document.getElementById('showHideLink3').addEventListener('click', function() {");
                out.println("            var shoppingList1 = document.querySelector('.book');");
                out.println("            var display = document.querySelector('.display');");
                out.println("            var shoppingList2 = document.querySelector('.computer');");
                out.println("            var shoppingList3 = document.querySelector('.music');");
                out.println("            if (shoppingList1.style.display === 'none') {");
                out.println("                shoppingList1.style.display = 'block';");
                out.println("                shoppingList2.style.display = 'none';");
                out.println("                shoppingList3.style.display = 'none';");
                out.println("                display.style.display = 'none';");
                out.println("            } else {");
                out.println("                display.style.display = 'none';");
                out.println("                shoppingList1.style.display = 'none';");
                out.println("                shoppingList2.style.display = 'none';");
                out.println("                shoppingList3.style.display = 'none';");
                out.println("            }");
                out.println("        });");
                out.println("    </script>");
                out.println("</body>");
                out.println("</html>");
        %>
    </body>
</html>
